name: task
description: "A Flutter App that displays a list of items and allows users to add, edit, and delete them."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  provider: ^6.1.5+1
  hive: ^2.2.3
  uuid: ^4.5.2
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  google_fonts: ^6.3.2
  flutter_switch: ^0.3.2
  animate_do: ^4.2.0
  animated_text_kit: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

